jobs:
    include:
        - language: objective-c
          osx_image: xcode13.1
          sudo: false
          install: skip
          script:
        - "rvm use 2.5.7 --install --binary --fuzzy"
        - "gem install jazzy"
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
