jobs:
    include:
        - language: objective-c
          osx_image: xcode13.1
          sudo: false

        - language: ruby
          rvm: 2.7.5
          install: skip
          script: ruby -v
