dist: focal

jobs:
    include:
        - language: objective-c
          osx_image: xcode13.1
          sudo: false
          install: skip
          script: 
           - xcrun instruments -s devices
           - /usr/bin/xcodebuild -version
           - xcrun simctl list devices

        - language: ruby
          rvm: 2.7.5
          install: skip
          script: ruby -v
